services:
  test: &default
    build:
      context: .
      target: base
    env_file:
      - ./env/common.env
      - ./env/dev.env
    volumes:
      - ./:/app

  api:
    build:
      context: .
      target: api
    container_name: segmentation-api-api
    ports:
      - "8080:8080"
    env_file:
      - ./env/common.env
      - ./env/dev.env
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

  api-dev:
    <<: *default
    container_name: segmentation-api-api-dev
    ports:
      - "8080:8080"
    entrypoint: ["air", "-c", ".air-api.toml"]
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

  processor:
    build:
      context: .
      target: processor
    container_name: segmentation-api-processor
    env_file:
      - ./env/common.env
      - ./env/dev.env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

  processor-dev:
    build:
      context: .
      target: base
    container_name: segmentation-api-processor-dev
    env_file:
      - ./env/common.env
      - ./env/dev.env
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./data:/app/data
    working_dir: /app
    entrypoint: ["air", "-c", ".air-processor.toml"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'  
          memory: '128M'    
    profiles:
      - dev

  processor-run:
    build:
      context: .
      target: base
    container_name: segmentation-api-processor-run
    env_file:
      - ./env/common.env
      - ./env/dev.env
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    command: /app/processor
    deploy:
      resources:
        limits:
          cpus: '1'  
          memory: '128M'
    profiles:
      - dev


  mysql-db:
    image: mysql:8.0
    env_file:
      - ./env/db.env
    command:
      - --default-authentication-plugin=caching_sha2_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
      - ./configs/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro        
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'  
          memory: '2G'    


  adminer:
    image: adminer:latest
    container_name: segmentation-api-adminer
    ports:
      - "8081:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql-db-data: